global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-app"
    static_configs:
      - targets: ["go-app:8080"]
        labels:
          service: "go-app"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
