global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-app"
    static_configs:
      - targets: ["go-app:8080"]
        labels:
          service: "go-app"

  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["spring-boot-app:8081"]
        labels:
            service: "spring-boot-app"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
