version: "3.0"

services:
  elasticsearch:
    container_name: elasticsearch-service
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - cluster.name=es-cluster
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-network
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-service
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-service:9200
    networks:
      - es-network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  es-data:
    driver: local

networks:
  es-network:
    driver: bridge
