# METRICBEAT CONFIG YAML REFERENCE
# https://github.com/elastic/beats/blob/master/metricbeat/metricbeat.reference.yml

# ========== AUTODISCOVERY ==========
# Autodiscover allows you to detect changes in the system and spawn new modules as they happen.
# https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# ========== MODULES ==========
metricbeat.modules:
  # SYSTEM MODULE
  - module: system
    metricsets:
      - cpu             # CPU usage
      - load            # CPU load averages
      - memory          # Memory usage
      - network         # Network IO
      - process         # Per process metrics
      - process_summary # Process summary
      - uptime          # System Uptime
      - socket_summary  # Socket summary
      #- core           # Per CPU core usage
      - diskio          # Disk IO
      - filesystem      # File system usage for each mountpoint
      #- fsstat         # File system summary metrics
      #- raid           # Raid
      #- socket         # Sockets and connection info (linux only)
      #- service        # systemd service information
    enabled: true
    period: 10s
    processes: ['.*']
    # Configure the metric types that are included by these metricsets.
    cpu.metrics:  ["percentages","normalized_percentages"]  # The other available option is ticks.
    core.metrics: ["percentages"]  # The other available option is ticks.

  # DOCKER MODULE
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # KAFKA MODULE
  - module: kafka
    metricsets:
      - broker
      - consumer
      - consumergroup
      - partition
      - producer
    period: 10s
    hosts: ["kafka:9092"]

# ========== PROCESSORS ==========
processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true

# ========== ELASTICSEARCH OUTPUT ==========
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

# ========== DASHBOARDS SETUP ==========
setup.dashboards:
  enabled: true

# ========== KIBANA SETUP ==========
setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

# ========== XPACK SECURITY ==========
xpack.monitoring:
  enabled: true
  elasticsearch:
