{
 "title": "Kafka Lag",
 "description": "Kafka Lag Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(kafka_consumergroup_group_lag)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "query_result(kafka_consumergroup_group_lag{kubernetes_namespace=\"$namespace\"})"
    }
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": {
     "query": "query_result(kafka_consumergroup_group_lag{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Consumer Group Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer Group Max Lag Seconds",
   "type": "timeseries",
   "description": "Max extrapolated lag in seconds for each consumer group.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(50, kafka_consumergroup_group_max_lag_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"})",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag By Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag_seconds) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Seconds",
   "type": "timeseries",
   "description": "Extrapolated lag in seconds for each partition.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag Partition Offsets",
   "type": "timeseries",
   "description": "Consumer Group Lag Partition Offsets",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(25, kafka_consumergroup_group_lag{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"})",
     "legendFormat": "{{group}},{{topic}},{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag In Time Per Group Over Offset Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "$consumer_group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "repeat": "consumer_group",
   "targets": [
    {
     "expr": "kafka_consumergroup_group_max_lag_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "kafka_consumergroup_group_max_lag{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"}",
     "legendFormat": "Consumer group lag in offsets"
    }
   ]
  },
  {
   "title": "Consumer Group Lag in Time Per Group Over Summed Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "$consumer_group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "consumer_group",
   "targets": [
    {
     "expr": "max(kafka_consumergroup_group_lag_seconds{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"}) by (group)",
     "legendFormat": "Consumer group lag in time"
    },
    {
     "expr": "sum(kafka_consumergroup_group_offset{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"})",
     "legendFormat": "Sum of group offsets"
    },
    {
     "expr": "sum((kafka_consumergroup_group_offset{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\",group=~\"$consumer_group\",group!=\"\"} * 0)\n+ on(namespace,cluster_name,topic,partition) group_left() kafka_partition_latest_offset{kubernetes_namespace=\"$namespace\",cluster_name=\"$cluster_name\"})",
     "legendFormat": "Sum of latest offsets"
    }
   ]
  },
  { "title": "Kafka Lag Exporter JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_bytes_used[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}